matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: cpp
    - os: osx
      osx_image: xcode9.1
      language: objective-c
      sudo: required

script:
  - swift build
  - swift test

before_install:
  - chmod ugo+x ./Scripts/InstallSwift.sh
  - . ./Scripts/InstallSwift.sh

notifications:
  email:
    on_success: change
    on_failure: change
